POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=boston

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=boston

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=new york

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=chicago

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=washington

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=washington

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=los angeles

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=san francisco

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=dallas

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=philadelphia

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=houston

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=miami

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=atlanta

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=detroit

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=seattle

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=phoenix

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=celeveland

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=beijing

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=shanghai

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

city=boston

###